# File Monitor Service Configuration

# The directory to monitor for file modifications
# This should be a valid directory path on the Windows system
monitor_directory: "C:\\path\\to\\monitor"

# How often to check for file modifications (in minutes)
# This should be an integer between 1 and 60
check_frequency: 5

# The API endpoint for remote reporting
# This should be a valid URL where the service will send the collected data
api_endpoint: "https://api.example.com/file-stats"

# Additional configuration options can be added here as needed
# For example:
# log_level: "info"
# max_log_size: 10 # in MB
# backup_count: 5 # number of log files to keep
