// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestFileModifications():Promise<string>;

export function GetOsqueryStatus():Promise<string>;

export function StartService():Promise<string>;

export function StopService():Promise<string>;
