// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestFileModifications() {
  return window['go']['main']['App']['GetLatestFileModifications']();
}

export function GetOsqueryStatus() {
  return window['go']['main']['App']['GetOsqueryStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
